config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "lists#index"

  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }, presence: true
  validates :list, presence: true
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  before_destroy :check_bookmarks

  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true, uniqueness: true

  private

  def check_bookmarks
    errors.add(:base, "Cannot delete movie with bookmarks") if bookmarks.exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end
  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
  def delete_bookmark(bookmark)
    link_to(bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'text-decoration-none text-reset') do
      content_tag(:span) do
        content_tag(:i, "", class: "fa-solid fa-x delete-icon")
      end
    end
  end
end

app/views/bookmarks/_bookmark.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.error_notification %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/bookmarks/new.html.erb
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.input :comment %>
      <%= f.association :movie %>
      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">WatchList</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Lists", root_path, class: "nav-link" %>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/_bookmark.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.error_notification %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/lists/index.html.erb
<div class="container my-3">
  <% if @lists.any? %>
    <div class="row">
      <% @lists.each do |list| %>
        <div class="col-6 col-md-4">
          <%= link_to list_path(list), class: 'text-decoration-none' do %>
            <div class="card my-3">
              <% if list.photo.attached? %>
                <%= cl_image_tag list.photo.key %>
              <% else %>
                <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPQDYau3Hs4-xw1i8jVSUY4BlF4FLmg8lQqg&usqp=CAU', class: 'card-img-top' %>
              <% end %>
              <div class="card-body">
                <h3 class="text-center"><%= list.name %></h3>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <h1>There are no lists</h1>
  <% end %>

  <%= link_to "Add", new_list_path, class: 'btn btn-primary mt-3' %>
</div>

app/views/lists/new.html.erb
<div class="container mt-5">
  <h2 class="text-center">
    New List
  </h2>
  <%= render 'form', locals: { list: @list } %>
</div>

app/views/lists/show.html.erb
<div class="container mt-5">
  <h2>
    <%= @list.name %>
  </h2>
  <div class="row">
    <% if @list.bookmarks.any? %>
      <% @list.bookmarks.each do |bookmark| %>
        <div class="col-6 col-md-4">
          <div class="card mb-3">
            <div class="card-body">
              <h3><%= bookmark.movie.title %></h3>
              <p><%= bookmark.comment %></p>
            </div>
            <div class="card-footer">
              <%= delete_bookmark(bookmark) %>
            </div>
          </div>
        </div>
    <% end %>
  <% else %>
    <div class="col-6 col-md-4">
      <h2>There are no bookmarks</h2>
    </div>
  <% end %>
  </div>
  <div class="col-6 col-md-4">
    <%= render "bookmark", locals: { list: @list, bookmark: @bookmark } %>
    <%= link_to "Delete List", list_path(@list), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger my-3' %>
  </div>
</div>